M48
; DRILL file {KiCad (6.0.11)} date Sun Feb 18 11:49:11 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-18T11:49:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.180
%
G90
G05
T1
X-12.0Y4.0
X-12.0Y-4.0
T2
X-11.43Y18.93
X-11.43Y-18.93
X26.43Y18.93
X26.43Y-18.93
T0
M30
